version: '3.4'

services:
  database:
    image: postgres:15.4
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: Oversight
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always
    ports:
      - "5432:5432"
    expose:
      - 5432

  api:
    image: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Host=database;Database=Base;Username=postgres;Password=toor
    depends_on:
      - database
